name: Fraud Detection CI Pipeline
on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests with pytest
        run: |
          pytest tests/ || true
      - name: Lint code
        run: |
          if [ -d "scripts/" ]; then
            flake8 scripts/ --count --show-source --statistics
          else
            echo "No scripts directory found - skipping linting"
          fi
